// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: knn.proto

package com.google.step.similarity;

public final class OrganizationsProtos {
  private OrganizationsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrganizationsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:similarity.Organizations)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
     */
    java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization> 
        getOrgsList();
    /**
     * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
     */
    com.google.step.similarity.OrganizationsProtos.Organizations.Organization getOrgs(int index);
    /**
     * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
     */
    int getOrgsCount();
    /**
     * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
     */
    java.util.List<? extends com.google.step.similarity.OrganizationsProtos.Organizations.OrganizationOrBuilder> 
        getOrgsOrBuilderList();
    /**
     * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
     */
    com.google.step.similarity.OrganizationsProtos.Organizations.OrganizationOrBuilder getOrgsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code similarity.Organizations}
   */
  public  static final class Organizations extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:similarity.Organizations)
      OrganizationsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Organizations.newBuilder() to construct.
    private Organizations(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Organizations() {
      orgs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Organizations(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                orgs_ = new java.util.ArrayList<com.google.step.similarity.OrganizationsProtos.Organizations.Organization>();
                mutable_bitField0_ |= 0x00000001;
              }
              orgs_.add(
                  input.readMessage(com.google.step.similarity.OrganizationsProtos.Organizations.Organization.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          orgs_ = java.util.Collections.unmodifiableList(orgs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.step.similarity.OrganizationsProtos.Organizations.class, com.google.step.similarity.OrganizationsProtos.Organizations.Builder.class);
    }

    public interface OrganizationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:similarity.Organizations.Organization)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
       */
      java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor> 
          getNeighborsList();
      /**
       * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
       */
      com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor getNeighbors(int index);
      /**
       * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
       */
      int getNeighborsCount();
      /**
       * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
       */
      java.util.List<? extends com.google.step.similarity.OrganizationsProtos.Organizations.Organization.NeighborOrBuilder> 
          getNeighborsOrBuilderList();
      /**
       * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
       */
      com.google.step.similarity.OrganizationsProtos.Organizations.Organization.NeighborOrBuilder getNeighborsOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code similarity.Organizations.Organization}
     */
    public  static final class Organization extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:similarity.Organizations.Organization)
        OrganizationOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Organization.newBuilder() to construct.
      private Organization(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Organization() {
        name_ = "";
        neighbors_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Organization(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  neighbors_ = new java.util.ArrayList<com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor>();
                  mutable_bitField0_ |= 0x00000002;
                }
                neighbors_.add(
                    input.readMessage(com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.parser(), extensionRegistry));
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            neighbors_ = java.util.Collections.unmodifiableList(neighbors_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_Organization_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_Organization_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.step.similarity.OrganizationsProtos.Organizations.Organization.class, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder.class);
      }

      public interface NeighborOrBuilder extends
          // @@protoc_insertion_point(interface_extends:similarity.Organizations.Organization.Neighbor)
          com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string name = 1;</code>
         */
        java.lang.String getName();
        /**
         * <code>string name = 1;</code>
         */
        com.google.protobuf.ByteString
            getNameBytes();
      }
      /**
       * Protobuf type {@code similarity.Organizations.Organization.Neighbor}
       */
      public  static final class Neighbor extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:similarity.Organizations.Organization.Neighbor)
          NeighborOrBuilder {
      private static final long serialVersionUID = 0L;
        // Use Neighbor.newBuilder() to construct.
        private Neighbor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
          super(builder);
        }
        private Neighbor() {
          name_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
          return this.unknownFields;
        }
        private Neighbor(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          this();
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          int mutable_bitField0_ = 0;
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  java.lang.String s = input.readStringRequireUtf8();

                  name_ = s;
                  break;
                }
                default: {
                  if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
          } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
          }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_Organization_Neighbor_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_Organization_Neighbor_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.class, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder.class);
        }

        public static final int NAME_FIELD_NUMBER = 1;
        private volatile java.lang.Object name_;
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }

        private byte memoizedIsInitialized = -1;
        @java.lang.Override
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return true;
          if (isInitialized == 0) return false;

          memoizedIsInitialized = 1;
          return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          if (!getNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
          }
          unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
          int size = memoizedSize;
          if (size != -1) return size;

          size = 0;
          if (!getNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
          }
          size += unknownFields.getSerializedSize();
          memoizedSize = size;
          return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
          if (obj == this) {
           return true;
          }
          if (!(obj instanceof com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor)) {
            return super.equals(obj);
          }
          com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor other = (com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor) obj;

          boolean result = true;
          result = result && getName()
              .equals(other.getName());
          result = result && unknownFields.equals(other.unknownFields);
          return result;
        }

        @java.lang.Override
        public int hashCode() {
          if (memoizedHashCode != 0) {
            return memoizedHashCode;
          }
          int hash = 41;
          hash = (19 * hash) + getDescriptor().hashCode();
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
          hash = (29 * hash) + unknownFields.hashCode();
          memoizedHashCode = hash;
          return hash;
        }

        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
        }
        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
          return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor prototype) {
          return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @java.lang.Override
        public Builder toBuilder() {
          return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        /**
         * Protobuf type {@code similarity.Organizations.Organization.Neighbor}
         */
        public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:similarity.Organizations.Organization.Neighbor)
            com.google.step.similarity.OrganizationsProtos.Organizations.Organization.NeighborOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_Organization_Neighbor_descriptor;
          }

          @java.lang.Override
          protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_Organization_Neighbor_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                    com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.class, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder.class);
          }

          // Construct using com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }

          private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
          }
          @java.lang.Override
          public Builder clear() {
            super.clear();
            name_ = "";

            return this;
          }

          @java.lang.Override
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_Organization_Neighbor_descriptor;
          }

          @java.lang.Override
          public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor getDefaultInstanceForType() {
            return com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.getDefaultInstance();
          }

          @java.lang.Override
          public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor build() {
            com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }

          @java.lang.Override
          public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor buildPartial() {
            com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor result = new com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor(this);
            result.name_ = name_;
            onBuilt();
            return result;
          }

          @java.lang.Override
          public Builder clone() {
            return (Builder) super.clone();
          }
          @java.lang.Override
          public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return (Builder) super.setField(field, value);
          }
          @java.lang.Override
          public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
          }
          @java.lang.Override
          public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
          }
          @java.lang.Override
          public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
          }
          @java.lang.Override
          public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
          }
          @java.lang.Override
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor) {
              return mergeFrom((com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }

          public Builder mergeFrom(com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor other) {
            if (other == com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.getDefaultInstance()) return this;
            if (!other.getName().isEmpty()) {
              name_ = other.name_;
              onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
          }

          @java.lang.Override
          public final boolean isInitialized() {
            return true;
          }

          @java.lang.Override
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor parsedMessage = null;
            try {
              parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              parsedMessage = (com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor) e.getUnfinishedMessage();
              throw e.unwrapIOException();
            } finally {
              if (parsedMessage != null) {
                mergeFrom(parsedMessage);
              }
            }
            return this;
          }

          private java.lang.Object name_ = "";
          /**
           * <code>string name = 1;</code>
           */
          public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
              com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
              java.lang.String s = bs.toStringUtf8();
              name_ = s;
              return s;
            } else {
              return (java.lang.String) ref;
            }
          }
          /**
           * <code>string name = 1;</code>
           */
          public com.google.protobuf.ByteString
              getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
              com.google.protobuf.ByteString b = 
                  com.google.protobuf.ByteString.copyFromUtf8(
                      (java.lang.String) ref);
              name_ = b;
              return b;
            } else {
              return (com.google.protobuf.ByteString) ref;
            }
          }
          /**
           * <code>string name = 1;</code>
           */
          public Builder setName(
              java.lang.String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  
            name_ = value;
            onChanged();
            return this;
          }
          /**
           * <code>string name = 1;</code>
           */
          public Builder clearName() {
            
            name_ = getDefaultInstance().getName();
            onChanged();
            return this;
          }
          /**
           * <code>string name = 1;</code>
           */
          public Builder setNameBytes(
              com.google.protobuf.ByteString value) {
            if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
            
            name_ = value;
            onChanged();
            return this;
          }
          @java.lang.Override
          public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
          }

          @java.lang.Override
          public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
          }


          // @@protoc_insertion_point(builder_scope:similarity.Organizations.Organization.Neighbor)
        }

        // @@protoc_insertion_point(class_scope:similarity.Organizations.Organization.Neighbor)
        private static final com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor DEFAULT_INSTANCE;
        static {
          DEFAULT_INSTANCE = new com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor();
        }

        public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor getDefaultInstance() {
          return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Neighbor>
            PARSER = new com.google.protobuf.AbstractParser<Neighbor>() {
          @java.lang.Override
          public Neighbor parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Neighbor(input, extensionRegistry);
          }
        };

        public static com.google.protobuf.Parser<Neighbor> parser() {
          return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Neighbor> getParserForType() {
          return PARSER;
        }

        @java.lang.Override
        public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor getDefaultInstanceForType() {
          return DEFAULT_INSTANCE;
        }

      }

      private int bitField0_;
      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int NEIGHBORS_FIELD_NUMBER = 2;
      private java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor> neighbors_;
      /**
       * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
       */
      public java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor> getNeighborsList() {
        return neighbors_;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
       */
      public java.util.List<? extends com.google.step.similarity.OrganizationsProtos.Organizations.Organization.NeighborOrBuilder> 
          getNeighborsOrBuilderList() {
        return neighbors_;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
       */
      public int getNeighborsCount() {
        return neighbors_.size();
      }
      /**
       * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
       */
      public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor getNeighbors(int index) {
        return neighbors_.get(index);
      }
      /**
       * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
       */
      public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.NeighborOrBuilder getNeighborsOrBuilder(
          int index) {
        return neighbors_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        for (int i = 0; i < neighbors_.size(); i++) {
          output.writeMessage(2, neighbors_.get(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        for (int i = 0; i < neighbors_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, neighbors_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.google.step.similarity.OrganizationsProtos.Organizations.Organization)) {
          return super.equals(obj);
        }
        com.google.step.similarity.OrganizationsProtos.Organizations.Organization other = (com.google.step.similarity.OrganizationsProtos.Organizations.Organization) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && getNeighborsList()
            .equals(other.getNeighborsList());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        if (getNeighborsCount() > 0) {
          hash = (37 * hash) + NEIGHBORS_FIELD_NUMBER;
          hash = (53 * hash) + getNeighborsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.google.step.similarity.OrganizationsProtos.Organizations.Organization prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code similarity.Organizations.Organization}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:similarity.Organizations.Organization)
          com.google.step.similarity.OrganizationsProtos.Organizations.OrganizationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_Organization_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_Organization_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.google.step.similarity.OrganizationsProtos.Organizations.Organization.class, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder.class);
        }

        // Construct using com.google.step.similarity.OrganizationsProtos.Organizations.Organization.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getNeighborsFieldBuilder();
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          if (neighborsBuilder_ == null) {
            neighbors_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            neighborsBuilder_.clear();
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_Organization_descriptor;
        }

        @java.lang.Override
        public com.google.step.similarity.OrganizationsProtos.Organizations.Organization getDefaultInstanceForType() {
          return com.google.step.similarity.OrganizationsProtos.Organizations.Organization.getDefaultInstance();
        }

        @java.lang.Override
        public com.google.step.similarity.OrganizationsProtos.Organizations.Organization build() {
          com.google.step.similarity.OrganizationsProtos.Organizations.Organization result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.google.step.similarity.OrganizationsProtos.Organizations.Organization buildPartial() {
          com.google.step.similarity.OrganizationsProtos.Organizations.Organization result = new com.google.step.similarity.OrganizationsProtos.Organizations.Organization(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.name_ = name_;
          if (neighborsBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              neighbors_ = java.util.Collections.unmodifiableList(neighbors_);
              bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.neighbors_ = neighbors_;
          } else {
            result.neighbors_ = neighborsBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.google.step.similarity.OrganizationsProtos.Organizations.Organization) {
            return mergeFrom((com.google.step.similarity.OrganizationsProtos.Organizations.Organization)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.google.step.similarity.OrganizationsProtos.Organizations.Organization other) {
          if (other == com.google.step.similarity.OrganizationsProtos.Organizations.Organization.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (neighborsBuilder_ == null) {
            if (!other.neighbors_.isEmpty()) {
              if (neighbors_.isEmpty()) {
                neighbors_ = other.neighbors_;
                bitField0_ = (bitField0_ & ~0x00000002);
              } else {
                ensureNeighborsIsMutable();
                neighbors_.addAll(other.neighbors_);
              }
              onChanged();
            }
          } else {
            if (!other.neighbors_.isEmpty()) {
              if (neighborsBuilder_.isEmpty()) {
                neighborsBuilder_.dispose();
                neighborsBuilder_ = null;
                neighbors_ = other.neighbors_;
                bitField0_ = (bitField0_ & ~0x00000002);
                neighborsBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getNeighborsFieldBuilder() : null;
              } else {
                neighborsBuilder_.addAllMessages(other.neighbors_);
              }
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.step.similarity.OrganizationsProtos.Organizations.Organization parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.google.step.similarity.OrganizationsProtos.Organizations.Organization) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor> neighbors_ =
          java.util.Collections.emptyList();
        private void ensureNeighborsIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            neighbors_ = new java.util.ArrayList<com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor>(neighbors_);
            bitField0_ |= 0x00000002;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.NeighborOrBuilder> neighborsBuilder_;

        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor> getNeighborsList() {
          if (neighborsBuilder_ == null) {
            return java.util.Collections.unmodifiableList(neighbors_);
          } else {
            return neighborsBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public int getNeighborsCount() {
          if (neighborsBuilder_ == null) {
            return neighbors_.size();
          } else {
            return neighborsBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor getNeighbors(int index) {
          if (neighborsBuilder_ == null) {
            return neighbors_.get(index);
          } else {
            return neighborsBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public Builder setNeighbors(
            int index, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor value) {
          if (neighborsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureNeighborsIsMutable();
            neighbors_.set(index, value);
            onChanged();
          } else {
            neighborsBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public Builder setNeighbors(
            int index, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder builderForValue) {
          if (neighborsBuilder_ == null) {
            ensureNeighborsIsMutable();
            neighbors_.set(index, builderForValue.build());
            onChanged();
          } else {
            neighborsBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public Builder addNeighbors(com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor value) {
          if (neighborsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureNeighborsIsMutable();
            neighbors_.add(value);
            onChanged();
          } else {
            neighborsBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public Builder addNeighbors(
            int index, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor value) {
          if (neighborsBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureNeighborsIsMutable();
            neighbors_.add(index, value);
            onChanged();
          } else {
            neighborsBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public Builder addNeighbors(
            com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder builderForValue) {
          if (neighborsBuilder_ == null) {
            ensureNeighborsIsMutable();
            neighbors_.add(builderForValue.build());
            onChanged();
          } else {
            neighborsBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public Builder addNeighbors(
            int index, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder builderForValue) {
          if (neighborsBuilder_ == null) {
            ensureNeighborsIsMutable();
            neighbors_.add(index, builderForValue.build());
            onChanged();
          } else {
            neighborsBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public Builder addAllNeighbors(
            java.lang.Iterable<? extends com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor> values) {
          if (neighborsBuilder_ == null) {
            ensureNeighborsIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, neighbors_);
            onChanged();
          } else {
            neighborsBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public Builder clearNeighbors() {
          if (neighborsBuilder_ == null) {
            neighbors_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
          } else {
            neighborsBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public Builder removeNeighbors(int index) {
          if (neighborsBuilder_ == null) {
            ensureNeighborsIsMutable();
            neighbors_.remove(index);
            onChanged();
          } else {
            neighborsBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder getNeighborsBuilder(
            int index) {
          return getNeighborsFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.NeighborOrBuilder getNeighborsOrBuilder(
            int index) {
          if (neighborsBuilder_ == null) {
            return neighbors_.get(index);  } else {
            return neighborsBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public java.util.List<? extends com.google.step.similarity.OrganizationsProtos.Organizations.Organization.NeighborOrBuilder> 
             getNeighborsOrBuilderList() {
          if (neighborsBuilder_ != null) {
            return neighborsBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(neighbors_);
          }
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder addNeighborsBuilder() {
          return getNeighborsFieldBuilder().addBuilder(
              com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.getDefaultInstance());
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder addNeighborsBuilder(
            int index) {
          return getNeighborsFieldBuilder().addBuilder(
              index, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.getDefaultInstance());
        }
        /**
         * <code>repeated .similarity.Organizations.Organization.Neighbor neighbors = 2;</code>
         */
        public java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder> 
             getNeighborsBuilderList() {
          return getNeighborsFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.NeighborOrBuilder> 
            getNeighborsFieldBuilder() {
          if (neighborsBuilder_ == null) {
            neighborsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Neighbor.Builder, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.NeighborOrBuilder>(
                    neighbors_,
                    ((bitField0_ & 0x00000002) == 0x00000002),
                    getParentForChildren(),
                    isClean());
            neighbors_ = null;
          }
          return neighborsBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:similarity.Organizations.Organization)
      }

      // @@protoc_insertion_point(class_scope:similarity.Organizations.Organization)
      private static final com.google.step.similarity.OrganizationsProtos.Organizations.Organization DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.google.step.similarity.OrganizationsProtos.Organizations.Organization();
      }

      public static com.google.step.similarity.OrganizationsProtos.Organizations.Organization getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Organization>
          PARSER = new com.google.protobuf.AbstractParser<Organization>() {
        @java.lang.Override
        public Organization parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Organization(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Organization> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Organization> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.step.similarity.OrganizationsProtos.Organizations.Organization getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ORGS_FIELD_NUMBER = 1;
    private java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization> orgs_;
    /**
     * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
     */
    public java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization> getOrgsList() {
      return orgs_;
    }
    /**
     * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
     */
    public java.util.List<? extends com.google.step.similarity.OrganizationsProtos.Organizations.OrganizationOrBuilder> 
        getOrgsOrBuilderList() {
      return orgs_;
    }
    /**
     * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
     */
    public int getOrgsCount() {
      return orgs_.size();
    }
    /**
     * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
     */
    public com.google.step.similarity.OrganizationsProtos.Organizations.Organization getOrgs(int index) {
      return orgs_.get(index);
    }
    /**
     * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
     */
    public com.google.step.similarity.OrganizationsProtos.Organizations.OrganizationOrBuilder getOrgsOrBuilder(
        int index) {
      return orgs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < orgs_.size(); i++) {
        output.writeMessage(1, orgs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < orgs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, orgs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.step.similarity.OrganizationsProtos.Organizations)) {
        return super.equals(obj);
      }
      com.google.step.similarity.OrganizationsProtos.Organizations other = (com.google.step.similarity.OrganizationsProtos.Organizations) obj;

      boolean result = true;
      result = result && getOrgsList()
          .equals(other.getOrgsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getOrgsCount() > 0) {
        hash = (37 * hash) + ORGS_FIELD_NUMBER;
        hash = (53 * hash) + getOrgsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.step.similarity.OrganizationsProtos.Organizations parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.step.similarity.OrganizationsProtos.Organizations parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.step.similarity.OrganizationsProtos.Organizations prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code similarity.Organizations}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:similarity.Organizations)
        com.google.step.similarity.OrganizationsProtos.OrganizationsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.step.similarity.OrganizationsProtos.Organizations.class, com.google.step.similarity.OrganizationsProtos.Organizations.Builder.class);
      }

      // Construct using com.google.step.similarity.OrganizationsProtos.Organizations.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOrgsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (orgsBuilder_ == null) {
          orgs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          orgsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.step.similarity.OrganizationsProtos.internal_static_similarity_Organizations_descriptor;
      }

      @java.lang.Override
      public com.google.step.similarity.OrganizationsProtos.Organizations getDefaultInstanceForType() {
        return com.google.step.similarity.OrganizationsProtos.Organizations.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.step.similarity.OrganizationsProtos.Organizations build() {
        com.google.step.similarity.OrganizationsProtos.Organizations result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.step.similarity.OrganizationsProtos.Organizations buildPartial() {
        com.google.step.similarity.OrganizationsProtos.Organizations result = new com.google.step.similarity.OrganizationsProtos.Organizations(this);
        int from_bitField0_ = bitField0_;
        if (orgsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            orgs_ = java.util.Collections.unmodifiableList(orgs_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.orgs_ = orgs_;
        } else {
          result.orgs_ = orgsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.step.similarity.OrganizationsProtos.Organizations) {
          return mergeFrom((com.google.step.similarity.OrganizationsProtos.Organizations)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.step.similarity.OrganizationsProtos.Organizations other) {
        if (other == com.google.step.similarity.OrganizationsProtos.Organizations.getDefaultInstance()) return this;
        if (orgsBuilder_ == null) {
          if (!other.orgs_.isEmpty()) {
            if (orgs_.isEmpty()) {
              orgs_ = other.orgs_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureOrgsIsMutable();
              orgs_.addAll(other.orgs_);
            }
            onChanged();
          }
        } else {
          if (!other.orgs_.isEmpty()) {
            if (orgsBuilder_.isEmpty()) {
              orgsBuilder_.dispose();
              orgsBuilder_ = null;
              orgs_ = other.orgs_;
              bitField0_ = (bitField0_ & ~0x00000001);
              orgsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOrgsFieldBuilder() : null;
            } else {
              orgsBuilder_.addAllMessages(other.orgs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.step.similarity.OrganizationsProtos.Organizations parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.step.similarity.OrganizationsProtos.Organizations) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization> orgs_ =
        java.util.Collections.emptyList();
      private void ensureOrgsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          orgs_ = new java.util.ArrayList<com.google.step.similarity.OrganizationsProtos.Organizations.Organization>(orgs_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.step.similarity.OrganizationsProtos.Organizations.Organization, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder, com.google.step.similarity.OrganizationsProtos.Organizations.OrganizationOrBuilder> orgsBuilder_;

      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization> getOrgsList() {
        if (orgsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(orgs_);
        } else {
          return orgsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public int getOrgsCount() {
        if (orgsBuilder_ == null) {
          return orgs_.size();
        } else {
          return orgsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public com.google.step.similarity.OrganizationsProtos.Organizations.Organization getOrgs(int index) {
        if (orgsBuilder_ == null) {
          return orgs_.get(index);
        } else {
          return orgsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public Builder setOrgs(
          int index, com.google.step.similarity.OrganizationsProtos.Organizations.Organization value) {
        if (orgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrgsIsMutable();
          orgs_.set(index, value);
          onChanged();
        } else {
          orgsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public Builder setOrgs(
          int index, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder builderForValue) {
        if (orgsBuilder_ == null) {
          ensureOrgsIsMutable();
          orgs_.set(index, builderForValue.build());
          onChanged();
        } else {
          orgsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public Builder addOrgs(com.google.step.similarity.OrganizationsProtos.Organizations.Organization value) {
        if (orgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrgsIsMutable();
          orgs_.add(value);
          onChanged();
        } else {
          orgsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public Builder addOrgs(
          int index, com.google.step.similarity.OrganizationsProtos.Organizations.Organization value) {
        if (orgsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOrgsIsMutable();
          orgs_.add(index, value);
          onChanged();
        } else {
          orgsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public Builder addOrgs(
          com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder builderForValue) {
        if (orgsBuilder_ == null) {
          ensureOrgsIsMutable();
          orgs_.add(builderForValue.build());
          onChanged();
        } else {
          orgsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public Builder addOrgs(
          int index, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder builderForValue) {
        if (orgsBuilder_ == null) {
          ensureOrgsIsMutable();
          orgs_.add(index, builderForValue.build());
          onChanged();
        } else {
          orgsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public Builder addAllOrgs(
          java.lang.Iterable<? extends com.google.step.similarity.OrganizationsProtos.Organizations.Organization> values) {
        if (orgsBuilder_ == null) {
          ensureOrgsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, orgs_);
          onChanged();
        } else {
          orgsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public Builder clearOrgs() {
        if (orgsBuilder_ == null) {
          orgs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          orgsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public Builder removeOrgs(int index) {
        if (orgsBuilder_ == null) {
          ensureOrgsIsMutable();
          orgs_.remove(index);
          onChanged();
        } else {
          orgsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder getOrgsBuilder(
          int index) {
        return getOrgsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public com.google.step.similarity.OrganizationsProtos.Organizations.OrganizationOrBuilder getOrgsOrBuilder(
          int index) {
        if (orgsBuilder_ == null) {
          return orgs_.get(index);  } else {
          return orgsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public java.util.List<? extends com.google.step.similarity.OrganizationsProtos.Organizations.OrganizationOrBuilder> 
           getOrgsOrBuilderList() {
        if (orgsBuilder_ != null) {
          return orgsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(orgs_);
        }
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder addOrgsBuilder() {
        return getOrgsFieldBuilder().addBuilder(
            com.google.step.similarity.OrganizationsProtos.Organizations.Organization.getDefaultInstance());
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder addOrgsBuilder(
          int index) {
        return getOrgsFieldBuilder().addBuilder(
            index, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.getDefaultInstance());
      }
      /**
       * <code>repeated .similarity.Organizations.Organization orgs = 1;</code>
       */
      public java.util.List<com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder> 
           getOrgsBuilderList() {
        return getOrgsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.step.similarity.OrganizationsProtos.Organizations.Organization, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder, com.google.step.similarity.OrganizationsProtos.Organizations.OrganizationOrBuilder> 
          getOrgsFieldBuilder() {
        if (orgsBuilder_ == null) {
          orgsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.step.similarity.OrganizationsProtos.Organizations.Organization, com.google.step.similarity.OrganizationsProtos.Organizations.Organization.Builder, com.google.step.similarity.OrganizationsProtos.Organizations.OrganizationOrBuilder>(
                  orgs_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          orgs_ = null;
        }
        return orgsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:similarity.Organizations)
    }

    // @@protoc_insertion_point(class_scope:similarity.Organizations)
    private static final com.google.step.similarity.OrganizationsProtos.Organizations DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.step.similarity.OrganizationsProtos.Organizations();
    }

    public static com.google.step.similarity.OrganizationsProtos.Organizations getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Organizations>
        PARSER = new com.google.protobuf.AbstractParser<Organizations>() {
      @java.lang.Override
      public Organizations parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Organizations(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Organizations> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Organizations> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.step.similarity.OrganizationsProtos.Organizations getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_similarity_Organizations_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_similarity_Organizations_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_similarity_Organizations_Organization_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_similarity_Organizations_Organization_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_similarity_Organizations_Organization_Neighbor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_similarity_Organizations_Organization_Neighbor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tknn.proto\022\nsimilarity\"\301\001\n\rOrganization" +
      "s\0224\n\004orgs\030\001 \003(\0132&.similarity.Organizatio" +
      "ns.Organization\032z\n\014Organization\022\014\n\004name\030" +
      "\001 \001(\t\022B\n\tneighbors\030\002 \003(\0132/.similarity.Or" +
      "ganizations.Organization.Neighbor\032\030\n\010Nei" +
      "ghbor\022\014\n\004name\030\001 \001(\tB1\n\032com.google.step.s" +
      "imilarityB\023OrganizationsProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_similarity_Organizations_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_similarity_Organizations_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_similarity_Organizations_descriptor,
        new java.lang.String[] { "Orgs", });
    internal_static_similarity_Organizations_Organization_descriptor =
      internal_static_similarity_Organizations_descriptor.getNestedTypes().get(0);
    internal_static_similarity_Organizations_Organization_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_similarity_Organizations_Organization_descriptor,
        new java.lang.String[] { "Name", "Neighbors", });
    internal_static_similarity_Organizations_Organization_Neighbor_descriptor =
      internal_static_similarity_Organizations_Organization_descriptor.getNestedTypes().get(0);
    internal_static_similarity_Organizations_Organization_Neighbor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_similarity_Organizations_Organization_Neighbor_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
